-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_type t
        JOIN pg_namespace n ON n.oid = t.typnamespace
        WHERE t.typname = 'enum_contents_content_type'
        AND n.nspname = 'public'
    ) THEN
        CREATE TYPE public.enum_contents_content_type AS ENUM (
            'image',
            'video',
            'news',
            'pdf',
            'advertisement'
        );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_type t
        JOIN pg_namespace n ON n.oid = t.typnamespace
        WHERE t.typname = 'enum_contents_status'
        AND n.nspname = 'public'
    ) THEN
        CREATE TYPE public.enum_contents_status AS ENUM (
            'active',
            'inactive'
        );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_type t
        JOIN pg_namespace n ON n.oid = t.typnamespace
        WHERE t.typname = 'enum_pdf_documents_extraction_status'
        AND n.nspname = 'public'
    ) THEN
        CREATE TYPE public.enum_pdf_documents_extraction_status AS ENUM (
            'processing',
            'completed',
            'failed'
        );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_type t
        JOIN pg_namespace n ON n.oid = t.typnamespace
        WHERE t.typname = 'enum_pdf_question_images_status'
        AND n.nspname = 'public'
    ) THEN
        CREATE TYPE public.enum_pdf_question_images_status AS ENUM (
            'active',
            'inactive'
        );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_type t
        JOIN pg_namespace n ON n.oid = t.typnamespace
        WHERE t.typname = 'enum_totem_contents_status'
        AND n.nspname = 'public'
    ) THEN
        CREATE TYPE public.enum_totem_contents_status AS ENUM (
            'active',
            'inactive'
        );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_type t
        JOIN pg_namespace n ON n.oid = t.typnamespace
        WHERE t.typname = 'enum_totem_question_sessions_status'
        AND n.nspname = 'public'
    ) THEN
        CREATE TYPE public.enum_totem_question_sessions_status AS ENUM (
            'active',
            'inactive',
            'ended',
            'expired'
        );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_type t
        JOIN pg_namespace n ON n.oid = t.typnamespace
        WHERE t.typname = 'enum_totem_question_sessions_end_reason'
        AND n.nspname = 'public'
    ) THEN
        CREATE TYPE public.enum_totem_question_sessions_end_reason AS ENUM (
            'timeout',
            'manual',
            'error',
            'completed'
        );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_type t
        JOIN pg_namespace n ON n.oid = t.typnamespace
        WHERE t.typname = 'enum_totems_state'
        AND n.nspname = 'public'
    ) THEN
        CREATE TYPE public.enum_totems_state AS ENUM (
            'active',
            'inactive'
        );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_type t
        JOIN pg_namespace n ON n.oid = t.typnamespace
        WHERE t.typname = 'enum_totems_connection_status'
        AND n.nspname = 'public'
    ) THEN
        CREATE TYPE public.enum_totems_connection_status AS ENUM (
            'online',
            'offline',
            'maintenance'
        );
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS public."SequelizeMeta"
(
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "SequelizeMeta_pkey" PRIMARY KEY (name)
);

CREATE TABLE IF NOT EXISTS public.app_user
(
    id serial NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying(150) COLLATE pg_catalog."default" NOT NULL,
    password_hash character varying(255) COLLATE pg_catalog."default",
    role character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'Admin'::character varying,
    status integer NOT NULL DEFAULT 2,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone,
    last_login_at timestamp with time zone,
    campus_id integer NOT NULL,
    CONSTRAINT app_user_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.campuses
(
    id serial NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT campuses_pkey PRIMARY KEY (id),
    CONSTRAINT campuses_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.contents
(
    id serial NOT NULL,
    title character varying(180) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    content_type enum_contents_content_type NOT NULL,
    file_url text COLLATE pg_catalog."default",
    status enum_contents_status NOT NULL DEFAULT 'active'::enum_contents_status,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone,
    campus_id integer NOT NULL,
    file_path character varying(500) COLLATE pg_catalog."default",
    file_provider character varying(40) COLLATE pg_catalog."default",
    file_mime_type character varying(200) COLLATE pg_catalog."default",
    file_size bigint,
    CONSTRAINT contents_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.notification
(
    id serial NOT NULL,
    title character varying(200) COLLATE pg_catalog."default" NOT NULL,
    message text COLLATE pg_catalog."default" NOT NULL,
    created_by integer NOT NULL,
    start_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    type character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'normal'::character varying,
    duration_minutes integer NOT NULL,
    target_scope character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'all'::character varying,
    end_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'active'::character varying,
    deleted_at timestamp with time zone,
    CONSTRAINT notification_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.notification_target
(
    id serial NOT NULL,
    notification_id integer NOT NULL,
    totem_id integer,
    campus_id integer,
    target_type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT notification_target_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.password_reset_token
(
    id serial NOT NULL,
    user_id integer NOT NULL,
    token_hash character varying(128) COLLATE pg_catalog."default" NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    used_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT password_reset_token_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.pdf_chunks
(
    id serial NOT NULL,
    pdf_document_id integer NOT NULL,
    chunk_order integer NOT NULL,
    question_text text COLLATE pg_catalog."default" NOT NULL,
    answer_text text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    question_key character varying(80) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pdf_chunks_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.pdf_documents
(
    id serial NOT NULL,
    content_id integer NOT NULL,
    file_url text COLLATE pg_catalog."default" NOT NULL,
    extraction_status enum_pdf_documents_extraction_status NOT NULL DEFAULT 'processing'::enum_pdf_documents_extraction_status,
    extracted_text text COLLATE pg_catalog."default",
    parsed_pairs_count integer NOT NULL DEFAULT 0,
    extraction_error text COLLATE pg_catalog."default",
    processed_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone,
    CONSTRAINT pdf_documents_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.pdf_question_images
(
    id serial NOT NULL,
    pdf_chunk_id integer NOT NULL,
    file_url text COLLATE pg_catalog."default" NOT NULL,
    sort_order integer NOT NULL DEFAULT 1,
    status enum_pdf_question_images_status NOT NULL DEFAULT 'active'::enum_pdf_question_images_status,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone,
    file_path character varying(500) COLLATE pg_catalog."default",
    file_provider character varying(40) COLLATE pg_catalog."default",
    file_mime_type character varying(200) COLLATE pg_catalog."default",
    file_size bigint,
    CONSTRAINT pdf_question_images_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.totem_contents
(
    id serial NOT NULL,
    totem_id integer NOT NULL,
    content_id integer NOT NULL,
    status enum_totem_contents_status NOT NULL DEFAULT 'active'::enum_totem_contents_status,
    start_at timestamp with time zone,
    end_at timestamp with time zone,
    priority integer NOT NULL DEFAULT 1,
    sort_order integer NOT NULL DEFAULT 1,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone,
    CONSTRAINT totem_contents_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.totem_device_sessions
(
    id serial NOT NULL,
    totem_id integer NOT NULL,
    access_token_hash character varying(128) COLLATE pg_catalog."default" NOT NULL,
    refresh_token_hash character varying(128) COLLATE pg_catalog."default" NOT NULL,
    access_token_expires_at timestamp with time zone NOT NULL,
    refresh_token_expires_at timestamp with time zone NOT NULL,
    linked_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_access_at timestamp with time zone,
    last_refreshed_at timestamp with time zone,
    revoked_at timestamp with time zone,
    revoked_reason character varying(120) COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT totem_device_sessions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.totem_question_sessions
(
    id serial NOT NULL,
    totem_id integer NOT NULL,
    status enum_totem_question_sessions_status NOT NULL DEFAULT 'active'::enum_totem_question_sessions_status,
    started_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_activity_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    inactivity_timeout_seconds integer NOT NULL,
    inactivity_deadline_at timestamp with time zone NOT NULL,
    ended_at timestamp with time zone,
    end_reason enum_totem_question_sessions_end_reason,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone,
    CONSTRAINT totem_question_sessions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.totems
(
    id serial NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    state enum_totems_state NOT NULL DEFAULT 'active'::enum_totems_state,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone,
    code character varying(50) COLLATE pg_catalog."default" NOT NULL,
    connection_status enum_totems_connection_status NOT NULL DEFAULT 'offline'::enum_totems_connection_status,
    last_seen_at timestamp with time zone,
    device_token character varying(128) COLLATE pg_catalog."default" NOT NULL,
    linking_code character varying(24) COLLATE pg_catalog."default",
    linking_code_generated_at timestamp with time zone,
    linking_code_expires_at timestamp with time zone,
    linking_code_used_at timestamp with time zone,
    linking_code_ttl_minutes integer,
    campus_id integer NOT NULL,
    CONSTRAINT totems_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.user_invitations
(
    id serial NOT NULL,
    user_id integer NOT NULL,
    token_hash character varying(128) COLLATE pg_catalog."default" NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    used_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT user_invitations_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.user_sessions
(
    sid character varying COLLATE pg_catalog."default" NOT NULL,
    sess json NOT NULL,
    expire timestamp(6) without time zone NOT NULL,
    CONSTRAINT session_pkey PRIMARY KEY (sid)
);

ALTER TABLE IF EXISTS public.app_user
    ADD CONSTRAINT app_user_campus_id_fkey FOREIGN KEY (campus_id)
    REFERENCES public.campuses (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS app_user_campus_id_idx
    ON public.app_user(campus_id);


ALTER TABLE IF EXISTS public.contents
    ADD CONSTRAINT contents_campus_id_fkey FOREIGN KEY (campus_id)
    REFERENCES public.campuses (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS contents_campus_id_idx
    ON public.contents(campus_id);


ALTER TABLE IF EXISTS public.notification
    ADD CONSTRAINT notification_created_by_fkey FOREIGN KEY (created_by)
    REFERENCES public.app_user (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS notification_created_by_idx
    ON public.notification(created_by);


ALTER TABLE IF EXISTS public.notification_target
    ADD CONSTRAINT notification_target_campus_id_fkey FOREIGN KEY (campus_id)
    REFERENCES public.campuses (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS notification_target_campus_id_idx
    ON public.notification_target(campus_id);


ALTER TABLE IF EXISTS public.password_reset_token
    ADD CONSTRAINT password_reset_token_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.app_user (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS password_reset_token_user_id_idx
    ON public.password_reset_token(user_id);


ALTER TABLE IF EXISTS public.pdf_chunks
    ADD CONSTRAINT pdf_chunks_pdf_document_id_fkey FOREIGN KEY (pdf_document_id)
    REFERENCES public.pdf_documents (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS pdf_chunks_pdf_document_id
    ON public.pdf_chunks(pdf_document_id);


ALTER TABLE IF EXISTS public.pdf_documents
    ADD CONSTRAINT pdf_documents_content_id_fkey FOREIGN KEY (content_id)
    REFERENCES public.contents (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS pdf_documents_content_id
    ON public.pdf_documents(content_id);


ALTER TABLE IF EXISTS public.pdf_question_images
    ADD CONSTRAINT pdf_question_images_pdf_chunk_id_fkey FOREIGN KEY (pdf_chunk_id)
    REFERENCES public.pdf_chunks (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS pdf_question_images_chunk_id_idx
    ON public.pdf_question_images(pdf_chunk_id);


ALTER TABLE IF EXISTS public.totem_contents
    ADD CONSTRAINT totem_contents_content_id_fkey FOREIGN KEY (content_id)
    REFERENCES public.contents (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS totem_contents_content_id
    ON public.totem_contents(content_id);

ALTER TABLE IF EXISTS public.totem_device_sessions
    ADD CONSTRAINT totem_device_sessions_totem_id_fkey FOREIGN KEY (totem_id)
    REFERENCES public.totems (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS totem_device_sessions_totem_id_idx
    ON public.totem_device_sessions(totem_id);


ALTER TABLE IF EXISTS public.totem_question_sessions
    ADD CONSTRAINT totem_question_sessions_totem_id_fkey FOREIGN KEY (totem_id)
    REFERENCES public.totems (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS totem_question_sessions_totem_id
    ON public.totem_question_sessions(totem_id);


ALTER TABLE IF EXISTS public.totems
    ADD CONSTRAINT totems_campus_id_fkey FOREIGN KEY (campus_id)
    REFERENCES public.campuses (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS totems_campus_id_idx
    ON public.totems(campus_id);

ALTER TABLE IF EXISTS public.user_invitations
    ADD CONSTRAINT user_invitations_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.app_user (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS user_invitations_user_id_idx
    ON public.user_invitations(user_id);

END;